sudo: required

services:
  - docker

script:
  - make build-image

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      make push-image
    fi
